### ISSUE TITLE
conflict with "Debug console tab" plugin

### ISSUE THREAD

**Issue by Konano** [bannergress/iitc-plugin#34]
If the "Debug console tab" plugin is enabled, it gets stuck here.
![image](https://github.com/bannergress/iitc-plugin/assets/22500116/5acc84ac-6fd8-45e5-98d4-5ce8fb1058ba)

This is the error message in the console.
![image](https://github.com/bannergress/iitc-plugin/assets/22500116/07547aef-ddc5-4b57-8d42-9e2737716e48)
![image](https://github.com/bannergress/iitc-plugin/assets/22500116/a5958f61-a25c-464d-bc2c-b817de25ae00)

**Comment by ewoerner** [comment]
Needs to be fixed in the debug plugin.
